GET http://localhost:8000/ping

### Fetch data diaries
GET http://localhost:8000/api/diaries

### Fetch diarie by id
GET http://localhost:8000/api/diaries/1

### Save a diary entry
POST http://localhost:8000/api/diaries
Content-Type: application/json

{
  "date": "2026-01-01",
  "weather": "windy",
  "visibility": "great",
  "comment": "It was cold"
}

### Sending wrong data
POST http://localhost:8000/api/diaries
Content-Type: application/json

{
  "date": "2026-01-01",
  "weather": "sunny",
  "visibility": "ok",
  "comment": "I think I saw the titanic"
}